### ISSUE TITLE
修正してほしい箇所

### ISSUE THREAD

**Issue by Sorakime** [Mf-3d/c.Monot#1]
どうも、もとのMonotの開発者Sorakimeです。
開発してくれるのは地球から飛び出ていきそうなくらいくらい嬉しいのですが、開いたときにウィンドウの名前の「by monochrome.」という表示を消してほしいです。src/index.htmlのtitle要素の内容とかindex.jsの10行目ですね。

あとpackage.jsonの内容もよく読んで、独自にカスタムしてほしいです。
あとはロゴとかも元のから変えてください。

また、README.mdに僕のリポジトリ（github.com/Sorakime/monot)へのリンクを設置してほしいです。

以上です

**Comment by Mf-3d** [comment]
把握しました。

**Comment by Sorakime** [comment]
リポジトリのリンクを設置、、、をお願いしたい
たびたび悪いんですがね、、、
